### ISSUE TITLE
EJDB2

### ISSUE THREAD

**Issue by adamansky** [Softmotions/ejdb#183]
Reimplement EJDB due to many limitations http://ejdb.org/doc/limitations.html and hardly-maintainable codebase.

## Current state

Used Binn (https://github.com/liteserver/binn) as internal data serialization format
:new: https://github.com/Softmotions/ejdb/tree/ejdb2

* [x] All software **MIT** licensed 
* [x] Free space management done: https://github.com/Softmotions/iowow
* [x] Key/value storage engine done http://iowow.io
* [x] WAL implemented in iowow 
* [x] [iowow](http://iowow.io) ported to Windows
* [x]  ~~#205~~ Implement rfc6902 and rfc6901
* [x] ~~#207~~ Implement JSON Merge Patch rfc7396 
* [x] ~~#206~~ Implement XPath/JSON pointer like query language
* [x] ~~#212~~ Finish EJDB2 core engine 
* [x] ~~#213~~ CRUD REST API
* [x] ~~#214~~ Websocket query API
* [x] ~~#215~~ CLI Client app
* [x] ~~#218~~ Index management, collections metadata access using remote API endpoint 
* [x] #220 Test cases for embedded lwre.c regexp library
* [x] #217 Minimal ejdb2 documentation 

**[EJDB 2.0 Milestone tickets](https://github.com/Softmotions/ejdb/milestone/3)**

**Comment by akaustel** [comment]
Sounds great! Looking forward to this.

**Comment by BigJoe01** [comment]
Hi, why don't use wiredtiger as data storage?

**Comment by akaustel** [comment]
@BigJoe01 WiredTiger seems interesting, but it would seem you cannot use it on iOS, due to GPL, would you agree? Additionally, is WiredTiger suitable for tiny databases, say ~10k entries, and what kind of memory footprint does it have?

**Comment by Extarys** [comment]
Any update on this or is it abandoned?

**Comment by aneeeshp** [comment]
Is this still in progress?

**Comment by adamansky** [comment]
Hi! We have released our new key/value storage http://iowow.io which will be used as backend for EJDB2. As soon as iowow WAL(Write Ahead Logging)  will be implemented we will start  EJDB2 core engine implementation. https://github.com/liteserver/binn proposed for internal JSON serialization. So work in progress, no so fast as all we want but we are going forward anyway.

**Comment by katyo** [comment]
Great news!

**Comment by adamansky** [comment]
EJDB 2.0 Beta released https://github.com/Softmotions/ejdb/blob/master/README.md
